### ISSUE TITLE
Rubocop?

### ISSUE THREAD

**Issue by damacus** [cparedes/opsview_rest#16]
Hey, so I was looking at running rubocop. 

Are there any style guidelines you want to keep to like the old pre-2.0 hash syntax you wish to keep?

**Comment by cparedes** [comment]
Hey, wanted to say thanks for the commits so far btw! 

I actually *don't* want to keep the old syntax style. :) I haven't had much time to modernize this library, so really appreciate the effort gone into fixing this up!

**Comment by damacus** [comment]
No problem! Who doesn't enjoy a bit of yak shaving on a Friday? ;)
